In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
cars=pd.read_csv('cars.csv')

In [5]:
cars

             brand  km_driven    fuel         owner  selling_price
0           Maruti     244533     LPG  Fourth Owner         365920
1           Datsun      94378     CNG  Fourth Owner        1154976
2             Jeep     215374     LPG  Second Owner         463465
3           Jaguar      84038  Petrol   Third Owner        2187485
4       Mitsubishi      17736     CNG  Second Owner        1577989
..             ...        ...     ...           ...            ...
295            Kia     157306     CNG  Second Owner        1073216
296  Mercedes-Benz      84457     CNG  Fourth Owner        1037800
297  Mercedes-Benz     217345  Petrol   Third Owner        1551770
298           Audi       7103     LPG  Second Owner        2205274
299           Opel      94338     CNG  Fourth Owner        1867428

[300 rows x 5 columns]

In [6]:
cars['brand'].nunique()

32

In [7]:
cars['brand'].value_counts()

brand
Kia              14
Opel             14
Datsun           14
Jeep             12
Mahindra         12
Volkswagen       12
Skoda            12
Chevrolet        12
Land             11
Ashok            10
Jaguar           10
Mitsubishi       10
Lexus            10
Mercedes-Benz    10
Isuzu            10
Maruti            9
Force             9
MG                9
Honda             9
BMW               9
Toyota            8
Peugeot           8
Fiat              8
Renault           8
Hyundai           8
Audi              7
Ambassador        7
Ford              7
Daewoo            6
Volvo             6
Nissan            5
Tata              4
Name: count, dtype: int64

In [8]:
# using pandas we also do ne hot in pandas
pd.get_dummies(cars,columns=['fuel','owner'],dtype=int)

             brand  km_driven  selling_price  ...  owner_Fourth Owner  owner_Second Owner  owner_Third Owner
0           Maruti     244533         365920  ...                   1                   0                  0
1           Datsun      94378        1154976  ...                   1                   0                  0
2             Jeep     215374         463465  ...                   0                   1                  0
3           Jaguar      84038        2187485  ...                   0                   0                  1
4       Mitsubishi      17736        1577989  ...                   0                   1                  0
..             ...        ...            ...  ...                 ...                 ...                ...
295            Kia     157306        1073216  ...                   0                   1                  0
296  Mercedes-Benz      84457        1037800  ...                   1                   0                  0
297  Mercedes-Benz     217345        1551770  ...                   0                   0                  1
298           Audi       7103        2205274  ...                   0                   1                  0
299           Opel      94338        1867428  ...                   1                   0                  0

[300 rows x 11 columns]

In [9]:
# so see the  the dataframe we convert fuel and onwerinto numerical data

In [10]:
# if we want  remove the multicollinearity in the dataframe OR  k-1 hot codeing

In [11]:
pd.get_dummies(cars,columns=['fuel','owner'],dtype=int,drop_first=True)

             brand  km_driven  selling_price  ...  owner_Fourth Owner  owner_Second Owner  owner_Third Owner
0           Maruti     244533         365920  ...                   1                   0                  0
1           Datsun      94378        1154976  ...                   1                   0                  0
2             Jeep     215374         463465  ...                   0                   1                  0
3           Jaguar      84038        2187485  ...                   0                   0                  1
4       Mitsubishi      17736        1577989  ...                   0                   1                  0
..             ...        ...            ...  ...                 ...                 ...                ...
295            Kia     157306        1073216  ...                   0                   1                  0
296  Mercedes-Benz      84457        1037800  ...                   1                   0                  0
297  Mercedes-Benz     217345        1551770  ...                   0                   0                  1
298           Audi       7103        2205274  ...                   0                   1                  0
299           Opel      94338        1867428  ...                   1                   0                  0

[300 rows x 9 columns]

In [12]:
#so now see one colume from each is remve

In [13]:
# if we use pandas we do like this but this have issue that thy dont remember any thing tht what col wechange so we dont use it is ml 
# so we use sklearn in ML for one hot encoding

In [14]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test=train_test_split(cars.iloc[:,0:4],cars.iloc[:,-1],test_size=0.2)

In [24]:
x_train     # it is al input

         brand  km_driven    fuel         owner
128       Ford       7409  Diesel   Third Owner
172       Jeep      95197     CNG  Fourth Owner
130     Nissan      47052  Petrol  Second Owner
36         BMW     188126     LPG  Fourth Owner
146      Volvo     151069  Diesel  Fourth Owner
..         ...        ...     ...           ...
213   Mahindra     158844  Petrol   Third Owner
92       Force     239567  Petrol   Third Owner
133  Chevrolet     202372  Diesel  Second Owner
271      Ashok      48384  Diesel   First Owner
170        BMW      88099  Diesel   First Owner

[240 rows x 4 columns]

In [25]:
y_test

208     194749
27      504923
25     2490708
243    1693740
267     389485
254    1698197
281     995636
7       865401
176     119684
209      81718
203    2358421
256    1128463
21     1553506
197     902966
175    1375610
16      835098
35     1302963
124    2309406
184     255768
272    1799050
165     883993
18      292273
56     2158607
88     1931640
166    1722607
249     626249
17      769597
9       209843
169    1182991
135    2488412
231     435416
201    1724436
158    1583680
127    1243755
104    1328035
110    1166175
90      342267
115    1371771
229    1795516
212    1598012
144      59741
76     1707403
278    1785084
106     417340
222     123479
73     1464801
68      842693
61      776764
194    2456447
248    2351743
198     242518
153    1680662
210     898289
12      361053
151     561856
137    2165650
11      954583
89      783198
181    1824379
188    1717506
Name: selling_price, dtype: int64

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
ohe=OneHotEncoder()
ohe.fit_transform(x_train[['fuel','owner']])   # it is spare matrix if we want to see we will convert into array

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 480 stored elements and shape (240, 8)>

In [28]:
 ohe.fit_transform(x_train[['fuel','owner']]).toarray()

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(240, 8))

In [31]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()
x_test_new=ohe.fit_transform(x_test[['fuel','owner']]).toarray()

In [32]:
x_train_new          # this data have  8 col and total is 11 so this only fuel,owner so we add the other col with this 'brand','km_driven'

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(240, 8))

In [33]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new,))    # so the 2 col are combine now with this data

array([['Ford', 7409, 0.0, ..., 0.0, 0.0, 1.0],
       ['Jeep', 95197, 1.0, ..., 1.0, 0.0, 0.0],
       ['Nissan', 47052, 0.0, ..., 0.0, 1.0, 0.0],
       ...,
       ['Chevrolet', 202372, 0.0, ..., 0.0, 1.0, 0.0],
       ['Ashok', 48384, 0.0, ..., 0.0, 0.0, 0.0],
       ['BMW', 88099, 0.0, ..., 0.0, 0.0, 0.0]],
      shape=(240, 10), dtype=object)

In [35]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new)).shape     # now see the col is now 10

(240, 10)

In [36]:
# now we remove the brands have less than 10 cars

In [37]:
counts=cars['brand'].value_counts()

In [38]:
counts

brand
Kia              14
Opel             14
Datsun           14
Jeep             12
Mahindra         12
Volkswagen       12
Skoda            12
Chevrolet        12
Land             11
Ashok            10
Jaguar           10
Mitsubishi       10
Lexus            10
Mercedes-Benz    10
Isuzu            10
Maruti            9
Force             9
MG                9
Honda             9
BMW               9
Toyota            8
Peugeot           8
Fiat              8
Renault           8
Hyundai           8
Audi              7
Ambassador        7
Ford              7
Daewoo            6
Volvo             6
Nissan            5
Tata              4
Name: count, dtype: int64

In [39]:
cars['brand'].nunique()
number=10

In [44]:
repl=counts[counts <=number].index

In [48]:
pd.get_dummies(cars['brand'].replace(repl,'uncommon'))

     Chevrolet  Datsun   Jeep    Kia   Land  Mahindra   Opel  Skoda  Volkswagen  uncommon
0        False   False  False  False  False     False  False  False       False      True
1        False    True  False  False  False     False  False  False       False     False
2        False   False   True  False  False     False  False  False       False     False
3        False   False  False  False  False     False  False  False       False      True
4        False   False  False  False  False     False  False  False       False      True
..         ...     ...    ...    ...    ...       ...    ...    ...         ...       ...
295      False   False  False   True  False     False  False  False       False     False
296      False   False  False  False  False     False  False  False       False      True
297      False   False  False  False  False     False  False  False       False      True
298      False   False  False  False  False     False  False  False       False      True
299      False   False  False  False  False     False   True  False       False     False

[300 rows x 10 columns]

In [ ]:
# now see the data frame car which is above 10 is have co and below 10 in remove and all are store in